from enum import Enum


def human_readable(value):
    value = value.replace('__1__', '_/_')
    value = value.replace('__2__', '_-_')
    value = value.replace('__3__', ',_')
    value = value.split('_')
    value = [word[0:1].upper() + word[1:].lower() for word in value]
    value = ' '.join(value).strip()
    return value


def to_choices(e):
    e_dict = dict(e.__members__)
    return [(e_dict[k].value, human_readable(k)) for k in e_dict]


class Gender(Enum):
    MALE = 1
    FEMALE = 2
    OTHER = 3


class MonthlyIncome(Enum):
    BETWEEN_10K_AND_25K = 1
    BETWEEN_25K_AND_50K = 2
    BETWEEN_50K_AND_100K = 3
    ABOVE_100K = 4


class GrossTurnover(Enum):
    BETWEEN_50_LACS_AND_1_CRORE = 1
    BETWEEN_1_CRORE_AND_2_CRORES = 2
    BETWEEN_2_CRORES_AND_5_CRORES = 3
    BETWEEN_5_CRORES_AND_10_CRORES = 4
    BETWEEN_10_CRORES_AND_50_CRORES = 5
    ABOVE_50_CRORE = 6


class HouseType(Enum):
    OWNED_BY_YOU = 1
    OWNED_BY_PARENTS = 2
    RENTED = 3


class EmploymentType(Enum):
    SALARIED = 1
    SELF_EMPLOYEED = 2
    RETIRED = 3


class LoanReason(Enum):
    WEDDING = 1
    MEDICAL = 2
    VEHICLE = 3
    EDUCATION = 4
    FURNITURE = 5
    ELECTRONICS = 6
    BUSINESS = 7
    OTHERS = 0


class IndiaStates(Enum):
    ANDHRA_PRADESH = 1
    ARUNACHAL_PRADESH = 2
    ASSAM = 3
    BIHAR = 4
    CHANDIGARH = 5
    CHHATTISGARH = 6
    DADRA_AND_NAGAR_HAVELI = 7
    DAMAN_AND_DIU = 8
    DELHI = 9
    GOA = 10
    GUJARAT = 11
    HARYANA = 12
    HIMACHAL_PRADESH = 13
    JAMMU_AND_KASHMIR = 14
    JHARKHAND = 15
    KARNATAKA = 16
    KERALA = 17
    MADHYA_PRADESH = 18
    MAHARASHTRA = 19
    MANIPUR = 20
    MEGHALAYA = 21
    MIZORAM = 22
    NAGALAND = 23
    ORISSA = 24
    PONDICHERRY = 25
    PUNJAB = 26
    RAJASTHAN = 27
    SIKKIM = 28
    TAMIL_NADU = 29
    TRIPURA = 30
    UTTAR_PRADESH = 31
    UTTARAKHAND = 32
    WEST_BENGAL = 33


class AddressType(Enum):
    CURRENT = 1
    PERMANENT = 2


class EducationLevel(Enum):
    HIGH_SCHOOl = 1
    DIPLOMA = 2
    GRADUATE = 3
    POST_GRADUATE = 4
    PROFESSIONAl = 5


class MaritalStatus(Enum):
    SINGLE = 1
    MARRIED = 2
    DIVORCED = 3
    WIDOWED = 4


class EmploymentIndustry(Enum):
    AGRICULTURE__1__FORESTRY__1__FISHING = 1
    METALS_AND_MINERALS = 2
    ENERGY_AND_UTILITIES = 3
    CONSTRUCTION__2__INDUSTRIAL_FACILITIES_AND_INFRASTRUCTURE = 4
    AEROSPACE_AND_DEFENSE = 6
    AUTOMOTIVE_AND_PARTS_MFG = 7
    BIOTECHNOLOGY__1__PHARMACEUTICALS = 8
    CHEMICALS__1__PETRO__2__CHEMICALS = 9
    CONSUMER_PACKAGED_GOODS_MANUFACTURING = 10
    ELECTRONICS__3__COMPONENTS__3__AND_SEMICONDUCTOR_MFG = 11
    MANUFACTURING__2__OTHER = 12
    PRINTING_AND_PUBLISHING = 13
    CLOTHING_AND_TEXTILE_MANUFACTURING = 14
    WHOLESALE_TRADE__1__IMPORT__2__EXPORT = 15
    RETAIL = 17
    TRAVEL__3__TRANSPORTATION_AND_TOURISM = 18
    TRANSPORT_AND_STORAGE__2__MATERIALS = 19
    INTERNET_SERVICES = 20
    BROADCASTING__3__MUSIC__3__AND_FILM = 21
    TELECOMMUNICATIONS_SERVICES = 22
    BANKING = 23
    INSURANCE = 24
    REAL_ESTATE__1__PROPERTY_MANAGEMENT = 26
    RENTAL_SERVICES = 27
    ACCOUNTING_AND_AUDITING_SERVICES = 28
    ADVERTISING_AND_PR_SERVICES = 29
    ARCHITECTURAL_AND_DESIGN_SERVICES = 30
    MANAGEMENT_CONSULTING_SERVICES = 31
    COMPUTER_HARDWARE = 32
    COMPUTER_SOFTWARE = 33
    LEGAL_SERVICES = 34
    WASTE_MANAGEMENT = 37
    EDUCATION = 38
    HEALTHCARE_SERVICES = 39
    PERFORMING_AND_FINE_ARTS = 42
    SPORTS_AND_PHYSICAL_RECREATION = 43
    HOTELS_AND_LODGING = 44
    RESTAURANT__1__FOOD_SERVICES = 45
    STAFFING__1__EMPLOYMENT_AGENCIES = 46
    NONPROFIT_CHARITABLE_ORGANIZATIONS = 47
    PERSONAL_AND_HOUSEHOLD_SERVICES = 48
    GOVERNMENT_AND_MILITARY = 50
    SECURITY_AND_SURVEILLANCE = 74
    AUTOMOTIVE_SALES_AND_REPAIR_SERVICES = 75
    BUSINESS_SERVICES__2__OTHER = 76
    INFORMATION_TECHNOLOGY_SERVICES = 77
    CONSTRUCTION__2__RESIDENTIAL_AND_COMMERCIAL__1__OFFICE = 78
    ENGINEERING_SERVICES = 79
    ENTERTAINMENT_VENUES_AND_THEATERS = 80
    FINANCIAL_SERVICES = 81
    FOOD_AND_BEVERAGE_PRODUCTION = 82
    MARINE_MFG_AND_SERVICES = 83
    MEDICAL_DEVICES_AND_SUPPLIES = 84
    OTHERS = 85


class EmploymentDuration(Enum):
    LESS_THAN_1_YEAR = 1
    BETWEEN_1_AND_2_YEARS = 2
    BETWEEN_3_AND_5_YEARS = 3
    BETWEEN_5_AND_7_YEARS = 4
    BETWEEN_7_AND_10_YEARS = 5
    BETWEEN_10_AND_15_YEARS = 6
    OVER_15_YEARS = 7


class AccountType(Enum):
    INDIVIDUAL = 1
    INSTITUTION = 2


class ApplicationType(Enum):
    INVOICE = 1
    LOAN = 2


class OtpType(Enum):
    EMAIL = 1
    TEXT = 2
