"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from google.oauth2 import service_account
import os

import mimetypes

mimetypes.add_type('text/css', ".css", True)
mimetypes.add_type('font/ttf', '.ttf', True)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q^26jp!+hau!t#$=t27c(84x5omyy%fx3q8%b_2b%1p1y7d#7j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.0.20', '219.91.133.101']

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '168.138.114.166', 'velocefintech.com', 'www.velocefintech.com']
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'veloce.apps.VeloceConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'veloce.views.utils.MenuInjectionMiddleware'
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'fintech1',
        'USER': 'postgres',
        'PASSWORD': 'VeloceInnov002',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'marketplace': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'marketplace1',
        'USER': 'postgres',
        'PASSWORD': 'VeloceInnov002',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
LOGIN_URL = '/login/vauth/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.logix.in'
EMAIL_PORT = 587

AUTHENTICATION_BACKENDS = [
    'veloce.oauth.VeloceOAuth2',
    'django.contrib.auth.backends.ModelBackend'
]

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'veloce.oauth.save_profile',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

SESSION_COOKIE_SAMESITE = None

SOCIAL_AUTH_VAUTH_KEY = 'hG5XBhRRLwz4SVxQ9KlG5OBWF390XvWyjkzA1v4k'
SOCIAL_AUTH_VAUTH_SECRET = '2cY8YoqIvv5QOaMCauGnQVNCnKtV7COHwr8tanLzuefD4Pdyrsx1CVKi17sXAeNdFSZwCWJFTX4PxhyZb2AkC5BoYWhdcCcfjuvVjfZNhRXFLFpYpmJTzemrblRm8OSp'
# OAUTH_URL = 'http://219.91.133.101:8085'
OAUTH_URL = 'http://192.168.0.20:7004'

CORS_ORIGIN_ALLOW_ALL = True
API_KEY = 'test_52094d4ffd4115d1b188bae2a4d'
AUTH_TOKEN = 'test_b371de0669cd716c3889e563d12'
veloce_roi = 2

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# secure proxy SSL header and secure cookies
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True

# session expire at browser close
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# wsgi scheme
# os.environ['wsgi.url_scheme'] = 'https'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
